name: CRON for clone count

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i -g @hyperjumptech/export-github-clones-views
      - shell: bash
        env:
          GITHUB_USERNAME: ${{ secrets.CC_GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.CC_GITHUB_PASSWORD }}
          MONGODB_URI: ${{ secrets.CC_MONGODB_URI }}
        run: |
          export-github-clones-views hyperjumptech/export-github-clones-views hyperjumptech/hansip-web hyperjumptech/procheck hyperjumptech/branch-preview hyperjumptech/grule-rule-engine hyperjumptech/hansip hyperjumptech/procheck-configs hyperjumptech/firebase-cronjob hyperjumptech/beda hyperjumptech/react-native-confetti hyperjumptech/js-urai hyperjumptech/universal-update-checker hyperjumptech/jiffy
